Reuse cloudscale image import completion poll logic from `vshn/managed-talos-workflows`

diff --git a/workflows/cloudscale/image-steps.yml b/workflows/cloudscale/image-steps.yml
--- a/workflows/cloudscale/image-steps.yml
+++ b/workflows/cloudscale/image-steps.yml
@@ -123,13 +123,57 @@ spells:
 
     echo "Importing image into Cloudscale..."
 
-    curl -i -H "$auth_header" \
+    import_resp=$(curl -fsSL -H "$auth_header" \
       -F url="$(mc share download --json "${INPUT_commodore_cluster_id}/${INPUT_commodore_cluster_id}-bootstrap-ignition/rhcos-${INPUT_image_major}.${INPUT_image_minor}.qcow2" | jq -r .url)" \
       -F name="RHCOS ${INPUT_image_major}.${INPUT_image_minor}" \
       "${target_zones}" \
       -F slug="rhcos-${INPUT_image_major}.${INPUT_image_minor}" \
       -F source_format=qcow2 \
       -F user_data_handling=pass-through \
-      https://api.cloudscale.ch/v1/custom-images/import
+      https://api.cloudscale.ch/v1/custom-images/import)
 
-    echo "Image import initiated. ⚠️ TODO: Poll for completion."
+    echo "Waiting for import to complete..."
+    import_id=$(jq -n -r --argjson import "$import_resp" '$import.uuid')
+    import_done=false
+    status="initializing"
+    step_exit=0
+    while ! $import_done; do
+      import_status_resp=$(curl -fsSL -H "$auth_header" \
+        "https://api.cloudscale.ch/v1/custom-images/import/${import_id}")
+      status=$(jq -n -r --argjson status "$import_status_resp" '$status.status')
+      case "$status" in
+        "started"|"in_progress")
+          echo -n "."
+          import_done=false
+          import_error=
+          ;;
+        "failed")
+          import_done=true
+          import_error="❌ $(jq -n -r --argjson status "$import_status_resp" '$status.error_message')"
+          step_exit=1
+          break
+          ;;
+        "success")
+          import_done=true
+          import_error=
+          break
+          ;;
+        *)
+          import_done=true
+          import_error="⚠️ Unknown import status '${status}', canceling wait for completion, please verify the import status manually!"
+          step_exit=0
+          break
+          ;;
+      esac
+      sleep 5
+    done
+    echo ""
+
+    echo "Import completed with status ${status}"
+    if [ -n "$import_error" ]; then
+      echo -e "\n$import_error"
+      exit "$step_exit"
+    else
+      echo -e "\n✅ Successfully imported image"
+    fi
+    sleep 0.1
